chore: sync main

diff --git a/.github/workflows/manifests-images-save-addons-arm64.yml b/.github/workflows/manifests-images-save-addons-arm64.yml
--- a/.github/workflows/manifests-images-save-addons-arm64.yml
+++ b/.github/workflows/manifests-images-save-addons-arm64.yml
@@ -44,7 +44,7 @@ jobs:
   save-images:
     runs-on: ubuntu-22.04
     outputs:
-      release-version: ${{ steps.manifests-images-save.outputs.release-version }}
+      release-versions: ${{ steps.manifests-images-save.outputs.release-versions }}
       image-name: ${{ steps.get-version.outputs.image-name }}
     steps:
       - name: Free disk space
@@ -111,8 +111,8 @@ jobs:
           echo "Free space:"
           df -h
           
-          RELEASE_VERSION=$(yq e "."${IMAGE_NAME}"[0].version" ${MANIFESTS_FILE})
-          echo "release-version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
+          RELEASE_VERSIONS=$(yq e '[.'${IMAGE_NAME}'[].version] | join("|")' ${MANIFESTS_FILE})
+          echo "release-versions=${RELEASE_VERSIONS}" >> $GITHUB_OUTPUT
 
       - uses: manyuanrong/setup-ossutil@v2.0
         with:
@@ -123,102 +123,134 @@ jobs:
       - name: get images size
         run: |
           docker images
-          du -sh ${{ steps.get-version.outputs.image-name }}-images-${{ steps.manifests-images-save.outputs.release-version }}.tar.gz 
+          RELEASE_VERSIONS="${{ steps.manifests-images-save.outputs.release-versions }}"
+          IMAGE_NAME="${{ steps.get-version.outputs.image-name }}"
+          for release_version in $(echo "${RELEASE_VERSIONS}" | sed 's/|/ /g'); do
+              du -sh ${IMAGE_NAME}-images-${release_version}.tar.gz 
+          done
 
       - name: Upload arm64 images to oss
         id: upload_to_oss
         run: |
-          IMAGE_PKG_NAME="${{ steps.get-version.outputs.image-name }}-images-${{ steps.manifests-images-save.outputs.release-version }}.tar.gz"
-          
-          upload_ret=0
-          for i in {1..10}; do
-              echo "ossutil cp ${IMAGE_PKG_NAME} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME} ..."
-              ossutil cp -rf ./${IMAGE_PKG_NAME} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME}
-              upload_ret=$?
-          
-              if [[ -d "ossutil_output" ]]; then
-                  ossutil_report_files=$(ls ossutil_output)
-                  if [[ -n "${ossutil_report_files}" ]]; then
-                      ossutil_report_file_name="$(ls ossutil_output/ossutil_report_*.report)"
-                      if [[ -n "${ossutil_report_file_name}" && -f "${ossutil_report_file_name}" ]]; then
-                          echo "cp ${IMAGE_PKG_NAME} to oss error, retry..."
-                          cat "${ossutil_report_file_name}"
-                          rm -rf ossutil_output/ossutil_report_*.report
-                          upload_ret=1
+          RELEASE_VERSIONS="${{ steps.manifests-images-save.outputs.release-versions }}"
+          IMAGE_NAME="${{ steps.get-version.outputs.image-name }}"
+          for release_version in $(echo "${RELEASE_VERSIONS}" | sed 's/|/ /g'); do
+              IMAGE_PKG_NAME="${IMAGE_NAME}-images-${release_version}.tar.gz"
+              
+              upload_ret=0
+              for i in {1..10}; do
+                  echo "ossutil cp ${IMAGE_PKG_NAME} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME} ..."
+                  ossutil cp -rf ./${IMAGE_PKG_NAME} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME}
+                  upload_ret=$?
+              
+                  if [[ -d "ossutil_output" ]]; then
+                      ossutil_report_files=$(ls ossutil_output)
+                      if [[ -n "${ossutil_report_files}" ]]; then
+                          ossutil_report_file_name="$(ls ossutil_output/ossutil_report_*.report)"
+                          if [[ -n "${ossutil_report_file_name}" && -f "${ossutil_report_file_name}" ]]; then
+                              echo "cp ${IMAGE_PKG_NAME} to oss error, retry..."
+                              cat "${ossutil_report_file_name}"
+                              rm -rf ossutil_output/ossutil_report_*.report
+                              upload_ret=1
+                          fi
                       fi
                   fi
-              fi
-              if [[ $upload_ret -eq 0 ]]; then
-                  break
-              fi
-              sleep 1
-          done
-          
-          if [[ $upload_ret -eq 0 ]]; then
-              echo "upload ${IMAGE_PKG_NAME} to oss successfully"
-          else
-              exit 1
-          fi
-          
-          IMAGE_PKG_NAME_MD="${IMAGE_PKG_NAME}.md5"
-          echo "upload ${IMAGE_PKG_NAME_MD} to oss ..."
-          upload_ret=0
-          for i in {1..10}; do
-              md5sum ${IMAGE_PKG_NAME} > ${IMAGE_PKG_NAME_MD}
-              md5sum_check=$(md5sum -c ${IMAGE_PKG_NAME_MD})
-              check_ret=$?
-              if [[ $check_ret -eq 0 && "${md5sum_check}" == *"OK" ]]; then
-                  echo "${md5sum_check}"
-              else
+                  if [[ $upload_ret -eq 0 ]]; then
+                      break
+                  fi
                   sleep 1
-                  continue
+              done
+              
+              if [[ $upload_ret -eq 0 ]]; then
+                  echo "upload ${IMAGE_PKG_NAME} to oss successfully"
+              else
+                  exit 1
               fi
-          
-              echo "ossutil cp ${IMAGE_PKG_NAME_MD} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_MD} ..."
-              ossutil cp -rf ./${IMAGE_PKG_NAME_MD} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_MD}
-              upload_ret=$?
-          
-              if [[ -d "ossutil_output" ]]; then
-                  ossutil_report_files=$(ls ossutil_output)
-                  if [[ -n "${ossutil_report_files}" ]]; then
-                      ossutil_report_file_name="$(ls ossutil_output/ossutil_report_*.report)"
-                      if [[ -n "${ossutil_report_file_name}" && -f "${ossutil_report_file_name}" ]]; then
-                          echo "cp ${IMAGE_PKG_NAME_MD} to oss error, retry..."
-                          cat "${ossutil_report_file_name}"
-                          rm -rf ossutil_output/ossutil_report_*.report
-                          upload_ret=1
+              
+              IMAGE_PKG_NAME_MD="${IMAGE_PKG_NAME}.md5"
+              echo "upload ${IMAGE_PKG_NAME_MD} to oss ..."
+              upload_ret=0
+              for i in {1..10}; do
+                  md5sum ${IMAGE_PKG_NAME} > ${IMAGE_PKG_NAME_MD}
+                  md5sum_check=$(md5sum -c ${IMAGE_PKG_NAME_MD})
+                  check_ret=$?
+                  if [[ $check_ret -eq 0 && "${md5sum_check}" == *"OK" ]]; then
+                      echo "${md5sum_check}"
+                  else
+                      sleep 1
+                      continue
+                  fi
+              
+                  echo "ossutil cp ${IMAGE_PKG_NAME_MD} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_MD} ..."
+                  ossutil cp -rf ./${IMAGE_PKG_NAME_MD} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_MD}
+                  upload_ret=$?
+              
+                  if [[ -d "ossutil_output" ]]; then
+                      ossutil_report_files=$(ls ossutil_output)
+                      if [[ -n "${ossutil_report_files}" ]]; then
+                          ossutil_report_file_name="$(ls ossutil_output/ossutil_report_*.report)"
+                          if [[ -n "${ossutil_report_file_name}" && -f "${ossutil_report_file_name}" ]]; then
+                              echo "cp ${IMAGE_PKG_NAME_MD} to oss error, retry..."
+                              cat "${ossutil_report_file_name}"
+                              rm -rf ossutil_output/ossutil_report_*.report
+                              upload_ret=1
+                          fi
                       fi
                   fi
-              fi
+                  if [[ $upload_ret -eq 0 ]]; then
+                      break
+                  fi
+                  sleep 1
+              done
+              
               if [[ $upload_ret -eq 0 ]]; then
-                  break
+                  echo "upload ${IMAGE_PKG_NAME_MD} to oss successfully"
               fi
-              sleep 1
           done
-          
-          if [[ $upload_ret -eq 0 ]]; then
-              echo "upload ${IMAGE_PKG_NAME_MD} to oss successfully"
-          fi
 
   save-result:
     runs-on: ubuntu-latest
     needs: [ save-images ]
     if: ${{ always() }}
     outputs:
-      image-pkg-name: ${{ steps.get_save_result.outputs.image_pkg_name }}
       save-result: ${{ steps.get_save_result.outputs.save_result }}
+      image-pkg-name: ${{ steps.get_save_result.outputs.image_pkg_name }}
+      image-pkg-name-1: ${{ steps.get_save_result.outputs.image_pkg_name_1 }}
+      image-pkg-name-2: ${{ steps.get_save_result.outputs.image_pkg_name_2 }}
+      image-pkg-name-3: ${{ steps.get_save_result.outputs.image_pkg_name_3 }}
     steps:
       - name: get save result
         id: get_save_result
         run: |
           SAVE_RESULT="error"
-          IMAGE_PKG_NAME="${{ needs.save-images.outputs.image-name }}-images-${{ needs.save-images.outputs.release-version }}.tar.gz"
+          version_index=0
+          IMAGE_NAME=${{ needs.save-images.outputs.image-name }}
+          RELEASE_VERSIONS="${{ needs.save-images.outputs.release-versions }}"
+          for release_version in $(echo "${RELEASE_VERSIONS}" | sed 's/|/ /g'); do
+              IMAGE_PKG_NAME="${IMAGE_NAME}-images-${release_version}.tar.gz"
+              IMAGE_PKG_NAME="http://kubeblocks-oss.${{ env.OSS_ENDPOINT }}/images/arm64/${IMAGE_PKG_NAME}"
+              echo "IMAGE_PKG_NAME: ${IMAGE_PKG_NAME}"
+              case $version_index in
+                  0)
+                      echo 'image_pkg_name='${IMAGE_PKG_NAME} >> $GITHUB_OUTPUT
+                  ;;
+                  1)
+                      echo 'image_pkg_name_1='${IMAGE_PKG_NAME} >> $GITHUB_OUTPUT
+                  ;;
+                  2)
+                      echo 'image_pkg_name_2='${IMAGE_PKG_NAME} >> $GITHUB_OUTPUT
+                  ;;
+                  3)
+                      echo 'image_pkg_name_3='${IMAGE_PKG_NAME} >> $GITHUB_OUTPUT
+                  ;;
+              esac
+              version_index=$(( $version_index + 1 ))
+          done
+          
           if [[ "${{ needs.save-images.result }}" == "success" ]]; then
               SAVE_RESULT="success"
-              IMAGE_PKG_NAME="http://kubeblocks-oss.${{ env.OSS_ENDPOINT }}/images/arm64/${IMAGE_PKG_NAME}"
           fi
           echo 'save_result='$SAVE_RESULT >> $GITHUB_OUTPUT
-          echo 'image_pkg_name='${IMAGE_PKG_NAME} >> $GITHUB_OUTPUT
 
   send-message:
     permissions:
@@ -231,4 +263,43 @@ jobs:
       TYPE: "2"
       BOT_TYPE: "package"
       CONTENT: "save image ${{ needs.save-result.outputs.image-pkg-name }} ${{ needs.save-result.outputs.save-result }}"
+    secrets: inherit
+
+  send-message-1:
+    permissions:
+      id-token: write
+      contents: read
+    needs: [ save-result ]
+    if: ${{ always() && needs.save-result.outputs.image-pkg-name-1 != '' }}
+    uses: apecloud-inc/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.0
+    with:
+      TYPE: "2"
+      BOT_TYPE: "package"
+      CONTENT: "save image ${{ needs.save-result.outputs.image-pkg-name-1 }} ${{ needs.save-result.outputs.save-result }}"
+    secrets: inherit
+
+  send-message-2:
+    permissions:
+      id-token: write
+      contents: read
+    needs: [ save-result ]
+    if: ${{ always() && needs.save-result.outputs.image-pkg-name-2 != '' }}
+    uses: apecloud-inc/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.0
+    with:
+      TYPE: "2"
+      BOT_TYPE: "package"
+      CONTENT: "save image ${{ needs.save-result.outputs.image-pkg-name-2 }} ${{ needs.save-result.outputs.save-result }}"
+    secrets: inherit
+
+  send-message-3:
+    permissions:
+      id-token: write
+      contents: read
+    needs: [ save-result ]
+    if: ${{ always() && needs.save-result.outputs.image-pkg-name-3 != '' }}
+    uses: apecloud-inc/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.0
+    with:
+      TYPE: "2"
+      BOT_TYPE: "package"
+      CONTENT: "save image ${{ needs.save-result.outputs.image-pkg-name-3 }} ${{ needs.save-result.outputs.save-result }}"
     secrets: inherit
