chore: sync release-2.0

diff --git a/.github/workflows/manifests-images-save-addons-arm64.yml b/.github/workflows/manifests-images-save-addons-arm64.yml
--- a/.github/workflows/manifests-images-save-addons-arm64.yml
+++ b/.github/workflows/manifests-images-save-addons-arm64.yml
@@ -9,7 +9,7 @@ on:
         required: true
         default: ''
       ENABLE_ADDONS:
-        description: 'Enable save addon images (e.g. apecloud-mysql|clickhouse|elasticsearch|kafka|mongodb|mysql|oceanbase|postgresql|qdrant|rabbitmq|redis|starrocks|zookeeper|damengdb|kingbase)'
+        description: 'Enable save addon images (e.g. clickhouse|elasticsearch|kafka|mongodb|mysql|oceanbase|postgresql|qdrant|rabbitmq|redis|starrocks|zookeeper|damengdb|kingbase)'
         type: string
         required: true
         default: ''
@@ -21,7 +21,7 @@ on:
         required: true
         default: ''
       ENABLE_ADDONS:
-        description: 'Enable save addon images (e.g. apecloud-mysql|clickhouse|elasticsearch|kafka|mongodb|mysql|oceanbase|postgresql|qdrant|rabbitmq|redis|starrocks|zookeeper|damengdb|kingbase)'
+        description: 'Enable save addon images (e.g. clickhouse|elasticsearch|kafka|mongodb|mysql|oceanbase|postgresql|qdrant|rabbitmq|redis|starrocks|zookeeper|damengdb|kingbase)'
         type: string
         required: true
         default: ''
@@ -42,26 +42,33 @@ env:
 
 jobs:
   save-images:
-    runs-on: [ self-hosted, arm-yq-runner ]
+    runs-on: ubuntu-22.04
     outputs:
-      release-version: ${{ steps.manifests-images-save.outputs.release-version }}
+      release-versions: ${{ steps.manifests-images-save.outputs.release-versions }}
       image-name: ${{ steps.get-version.outputs.image-name }}
-      runner-name: ${{ steps.get_runner_name.outputs.runner-name }}
     steps:
-      - name: setup ossutil
-        continue-on-error: true
+      - name: Free disk space
         run: |
-          sudo apt-get update
-          sudo apt-get install unzip
-          sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
-
-      - name: ossutil config
-        env:
-          OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
-          OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}
-        run: |
-          ossutil config --access-key-id="${{ env.OSS_KEY_ID }}" --access-key-secret="${{ env.OSS_KEY_SECRET }}" --endpoint="${{ env.OSS_ENDPOINT }}"
-
+          echo "Free space first:"
+          df -h
+          
+          mnt_storage=$(df -h | (grep "/mnt" | grep "100%" ||true))
+          if [[ -n "${mnt_storage}" ]]; then
+            echo "Disk is full, please rerun the workflow."
+            exit 1
+          fi
+          
+          sudo mkdir -p /mnt/new-storage
+          sudo touch /etc/docker/daemon.json
+          sudo tee /etc/docker/daemon.json <<EOF
+          {
+            "data-root": "/mnt/new-storage"
+          }
+          EOF
+          sudo systemctl restart docker
+          echo "Free space second:"
+          df -h
+      
       - name: get version
         id: get-version
         run: |
@@ -84,7 +91,7 @@ jobs:
           ref: ${{ steps.get-version.outputs.release-version }}
 
       - uses: docker/setup-qemu-action@v3
-      - if: ${{ env.DOCKER_USER != '' && env.DOCKER_PASSWORD != '' && (inputs.ENABLE_ADDONS == 'damengdb' || inputs.ENABLE_ADDONS == 'goldendb') }}
+      - if: ${{ env.DOCKER_USER != '' && env.DOCKER_PASSWORD != '' && (inputs.ENABLE_ADDONS == 'damengdb' || inputs.ENABLE_ADDONS == 'goldendb' || inputs.ENABLE_ADDONS == 'oceanbase' || inputs.ENABLE_ADDONS == 'hadoop' || inputs.ENABLE_ADDONS == 'hive' || inputs.ENABLE_ADDONS == 'kubeblocks-enterprise' || inputs.ENABLE_ADDONS == 'ape-local-csi-driver' || inputs.ENABLE_ADDONS == '') }}
         name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
@@ -101,82 +108,149 @@ jobs:
           echo "save addons manifests images"
           bash .github/scripts/manifests_addons_images_save.sh "${MANIFESTS_FILE}" "${IMAGE_NAME}" "true"
           
-          RELEASE_VERSION=$(yq e "."${IMAGE_NAME}"[0].version" ${MANIFESTS_FILE})
-          echo "release-version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
+          echo "Free space:"
+          df -h
+          
+          RELEASE_VERSIONS=$(yq e '[.'${IMAGE_NAME}'[].version] | join("|")' ${MANIFESTS_FILE})
+          echo "release-versions=${RELEASE_VERSIONS}" >> $GITHUB_OUTPUT
+
+      - uses: manyuanrong/setup-ossutil@v2.0
+        with:
+          access-key-id: "${{ env.OSS_KEY_ID }}"
+          access-key-secret: "${{ env.OSS_KEY_SECRET }}"
+          endpoint: "${{ env.OSS_ENDPOINT }}"
 
       - name: get images size
         run: |
           docker images
-          du -sh ${{ steps.get-version.outputs.image-name }}-images-${{ steps.manifests-images-save.outputs.release-version }}.tar.gz 
+          RELEASE_VERSIONS="${{ steps.manifests-images-save.outputs.release-versions }}"
+          IMAGE_NAME="${{ steps.get-version.outputs.image-name }}"
+          for release_version in $(echo "${RELEASE_VERSIONS}" | sed 's/|/ /g'); do
+              du -sh ${IMAGE_NAME}-images-${release_version}.tar.gz 
+          done
 
       - name: Upload arm64 images to oss
         id: upload_to_oss
         run: |
-          IMAGE_PKG_NAME="${{ steps.get-version.outputs.image-name }}-images-${{ steps.manifests-images-save.outputs.release-version }}.tar.gz"
-          
-          upload_ret=0
-          for i in {1..10}; do
-              echo "ossutil cp ${IMAGE_PKG_NAME} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME} ..."
-              ossutil cp -rf ./${IMAGE_PKG_NAME} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME}  --read-timeout=420 --retry-times=5
-              upload_ret=$?
-          
-              if [[ -d "ossutil_output" ]]; then
-                  ossutil_report_files=$(ls ossutil_output)
-                  if [[ -n "${ossutil_report_files}" ]]; then
-                      ossutil_report_file_name="$(ls ossutil_output/ossutil_report_*.report)"
-                      if [[ -n "${ossutil_report_file_name}" && -f "${ossutil_report_file_name}" ]]; then
-                          echo "cp ${IMAGE_PKG_NAME} to oss error, retry..."
-                          cat "${ossutil_report_file_name}"
-                          rm -rf ossutil_output/ossutil_report_*.report
-                          upload_ret=1
+          RELEASE_VERSIONS="${{ steps.manifests-images-save.outputs.release-versions }}"
+          IMAGE_NAME="${{ steps.get-version.outputs.image-name }}"
+          for release_version in $(echo "${RELEASE_VERSIONS}" | sed 's/|/ /g'); do
+              IMAGE_PKG_NAME="${IMAGE_NAME}-images-${release_version}.tar.gz"
+              
+              upload_ret=0
+              for i in {1..10}; do
+                  echo "ossutil cp ${IMAGE_PKG_NAME} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME} ..."
+                  ossutil cp -rf ./${IMAGE_PKG_NAME} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME}
+                  upload_ret=$?
+              
+                  if [[ -d "ossutil_output" ]]; then
+                      ossutil_report_files=$(ls ossutil_output)
+                      if [[ -n "${ossutil_report_files}" ]]; then
+                          ossutil_report_file_name="$(ls ossutil_output/ossutil_report_*.report)"
+                          if [[ -n "${ossutil_report_file_name}" && -f "${ossutil_report_file_name}" ]]; then
+                              echo "cp ${IMAGE_PKG_NAME} to oss error, retry..."
+                              cat "${ossutil_report_file_name}"
+                              rm -rf ossutil_output/ossutil_report_*.report
+                              upload_ret=1
+                          fi
                       fi
                   fi
-              fi
+                  if [[ $upload_ret -eq 0 ]]; then
+                      break
+                  fi
+                  sleep 1
+              done
+              
               if [[ $upload_ret -eq 0 ]]; then
-                  break
+                  echo "upload ${IMAGE_PKG_NAME} to oss successfully"
+              else
+                  exit 1
               fi
-              sleep 1
+              
+              IMAGE_PKG_NAME_MD="${IMAGE_PKG_NAME}.md5"
+              echo "upload ${IMAGE_PKG_NAME_MD} to oss ..."
+              upload_ret=0
+              for i in {1..10}; do
+                  md5sum ${IMAGE_PKG_NAME} > ${IMAGE_PKG_NAME_MD}
+                  md5sum_check=$(md5sum -c ${IMAGE_PKG_NAME_MD})
+                  check_ret=$?
+                  if [[ $check_ret -eq 0 && "${md5sum_check}" == *"OK" ]]; then
+                      echo "${md5sum_check}"
+                  else
+                      sleep 1
+                      continue
+                  fi
+              
+                  echo "ossutil cp ${IMAGE_PKG_NAME_MD} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_MD} ..."
+                  ossutil cp -rf ./${IMAGE_PKG_NAME_MD} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_MD}
+                  upload_ret=$?
+              
+                  if [[ -d "ossutil_output" ]]; then
+                      ossutil_report_files=$(ls ossutil_output)
+                      if [[ -n "${ossutil_report_files}" ]]; then
+                          ossutil_report_file_name="$(ls ossutil_output/ossutil_report_*.report)"
+                          if [[ -n "${ossutil_report_file_name}" && -f "${ossutil_report_file_name}" ]]; then
+                              echo "cp ${IMAGE_PKG_NAME_MD} to oss error, retry..."
+                              cat "${ossutil_report_file_name}"
+                              rm -rf ossutil_output/ossutil_report_*.report
+                              upload_ret=1
+                          fi
+                      fi
+                  fi
+                  if [[ $upload_ret -eq 0 ]]; then
+                      break
+                  fi
+                  sleep 1
+              done
+              
+              if [[ $upload_ret -eq 0 ]]; then
+                  echo "upload ${IMAGE_PKG_NAME_MD} to oss successfully"
+              fi
           done
-          
-          if [[ $upload_ret -eq 0 ]]; then
-              echo "upload ${IMAGE_PKG_NAME} to oss successfully"
-          else
-              exit 1
-          fi
-
-      - name: get self runner name
-        id: get_runner_name
-        if: ${{ always() }}
-        run: |
-          echo runner-name=${RUNNER_NAME} >> $GITHUB_OUTPUT
-
-  delete-self-runner:
-    if: ${{ always() }}
-    needs: [ save-images ]
-    uses: apecloud-inc/apecloud-cd/.github/workflows/delete-self-runner.yml@v0.5.0
-    with:
-      RUNNER_NAME: "${{ needs.save-images.outputs.runner-name }}"
-    secrets: inherit
 
   save-result:
     runs-on: ubuntu-latest
     needs: [ save-images ]
     if: ${{ always() }}
     outputs:
-      image-pkg-name: ${{ steps.get_save_result.outputs.image_pkg_name }}
       save-result: ${{ steps.get_save_result.outputs.save_result }}
+      image-pkg-name: ${{ steps.get_save_result.outputs.image_pkg_name }}
+      image-pkg-name-1: ${{ steps.get_save_result.outputs.image_pkg_name_1 }}
+      image-pkg-name-2: ${{ steps.get_save_result.outputs.image_pkg_name_2 }}
+      image-pkg-name-3: ${{ steps.get_save_result.outputs.image_pkg_name_3 }}
     steps:
       - name: get save result
         id: get_save_result
         run: |
           SAVE_RESULT="error"
-          IMAGE_PKG_NAME="${{ needs.save-images.outputs.image-name }}-images-${{ needs.save-images.outputs.release-version }}.tar.gz"
+          version_index=0
+          IMAGE_NAME=${{ needs.save-images.outputs.image-name }}
+          RELEASE_VERSIONS="${{ needs.save-images.outputs.release-versions }}"
+          for release_version in $(echo "${RELEASE_VERSIONS}" | sed 's/|/ /g'); do
+              IMAGE_PKG_NAME="${IMAGE_NAME}-images-${release_version}.tar.gz"
+              IMAGE_PKG_NAME="http://kubeblocks-oss.${{ env.OSS_ENDPOINT }}/images/arm64/${IMAGE_PKG_NAME}"
+              echo "IMAGE_PKG_NAME: ${IMAGE_PKG_NAME}"
+              case $version_index in
+                  0)
+                      echo 'image_pkg_name='${IMAGE_PKG_NAME} >> $GITHUB_OUTPUT
+                  ;;
+                  1)
+                      echo 'image_pkg_name_1='${IMAGE_PKG_NAME} >> $GITHUB_OUTPUT
+                  ;;
+                  2)
+                      echo 'image_pkg_name_2='${IMAGE_PKG_NAME} >> $GITHUB_OUTPUT
+                  ;;
+                  3)
+                      echo 'image_pkg_name_3='${IMAGE_PKG_NAME} >> $GITHUB_OUTPUT
+                  ;;
+              esac
+              version_index=$(( $version_index + 1 ))
+          done
+          
           if [[ "${{ needs.save-images.result }}" == "success" ]]; then
               SAVE_RESULT="success"
-              IMAGE_PKG_NAME="http://kubeblocks-oss.${{ env.OSS_ENDPOINT }}/images/arm64/${IMAGE_PKG_NAME}"
           fi
           echo 'save_result='$SAVE_RESULT >> $GITHUB_OUTPUT
-          echo 'image_pkg_name='${IMAGE_PKG_NAME} >> $GITHUB_OUTPUT
 
   send-message:
     permissions:
@@ -189,4 +263,43 @@ jobs:
       TYPE: "2"
       BOT_TYPE: "package"
       CONTENT: "save image ${{ needs.save-result.outputs.image-pkg-name }} ${{ needs.save-result.outputs.save-result }}"
+    secrets: inherit
+
+  send-message-1:
+    permissions:
+      id-token: write
+      contents: read
+    needs: [ save-result ]
+    if: ${{ always() && needs.save-result.outputs.image-pkg-name-1 != '' }}
+    uses: apecloud-inc/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.0
+    with:
+      TYPE: "2"
+      BOT_TYPE: "package"
+      CONTENT: "save image ${{ needs.save-result.outputs.image-pkg-name-1 }} ${{ needs.save-result.outputs.save-result }}"
+    secrets: inherit
+
+  send-message-2:
+    permissions:
+      id-token: write
+      contents: read
+    needs: [ save-result ]
+    if: ${{ always() && needs.save-result.outputs.image-pkg-name-2 != '' }}
+    uses: apecloud-inc/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.0
+    with:
+      TYPE: "2"
+      BOT_TYPE: "package"
+      CONTENT: "save image ${{ needs.save-result.outputs.image-pkg-name-2 }} ${{ needs.save-result.outputs.save-result }}"
+    secrets: inherit
+
+  send-message-3:
+    permissions:
+      id-token: write
+      contents: read
+    needs: [ save-result ]
+    if: ${{ always() && needs.save-result.outputs.image-pkg-name-3 != '' }}
+    uses: apecloud-inc/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.0
+    with:
+      TYPE: "2"
+      BOT_TYPE: "package"
+      CONTENT: "save image ${{ needs.save-result.outputs.image-pkg-name-3 }} ${{ needs.save-result.outputs.save-result }}"
     secrets: inherit
diff --git a/.github/workflows/manifests-images-save-arm64.yml b/.github/workflows/manifests-images-save-arm64.yml
--- a/.github/workflows/manifests-images-save-arm64.yml
+++ b/.github/workflows/manifests-images-save-arm64.yml
@@ -1,4 +1,4 @@
-name: Manifests Images Save  Arm64
+name: Manifests Images Save Arm64
 
 on:
   workflow_dispatch:
@@ -17,7 +17,7 @@ on:
           - false
           - true
       ENABLE_ADDONS:
-        description: 'Enable save addon images (e.g. apecloud-mysql|clickhouse|elasticsearch|kafka|mongodb|mysql|oceanbase|postgresql|qdrant|rabbitmq|redis|starrocks|zookeeper|damengdb|kingbase)'
+        description: 'Enable save addon images (e.g. clickhouse|elasticsearch|kafka|mongodb|mysql|oceanbase|postgresql|qdrant|rabbitmq|redis|starrocks|zookeeper|damengdb|kingbase)'
         type: string
         required: false
         default: ''
@@ -34,7 +34,7 @@ on:
         type: string
         required: true
       ENABLE_ADDONS:
-        description: 'Enable save addon images (e.g. apecloud-mysql|clickhouse|elasticsearch|kafka|mongodb|mysql|oceanbase|postgresql|qdrant|rabbitmq|redis|starrocks|zookeeper|damengdb|kingbase)'
+        description: 'Enable save addon images (e.g. clickhouse|elasticsearch|kafka|mongodb|mysql|oceanbase|postgresql|qdrant|rabbitmq|redis|starrocks|zookeeper|damengdb|kingbase)'
         type: string
         required: false
         default: ''
@@ -56,26 +56,33 @@ env:
 
 jobs:
   save-images:
-    runs-on: [ self-hosted, arm-yq-runner ]
+    runs-on: ubuntu-22.04
     outputs:
       release-version: ${{ steps.get-version.outputs.release-version }}
       image-name: ${{ steps.get-image-name.outputs.image-name }}
-      runner-name: ${{ steps.get_runner_name.outputs.runner-name }}
     steps:
-      - name: setup ossutil
-        continue-on-error: true
+      - name: Free disk space
         run: |
-          sudo apt-get update
-          sudo apt-get install unzip
-          sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
-
-      - name: ossutil config
-        env:
-          OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
-          OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}
-        run: |
-          ossutil config --access-key-id="${{ env.OSS_KEY_ID }}" --access-key-secret="${{ env.OSS_KEY_SECRET }}" --endpoint="${{ env.OSS_ENDPOINT }}"
-
+          echo "Free space first:"
+          df -h
+          
+          mnt_storage=$(df -h | (grep "/mnt" | grep "100%" ||true))
+          if [[ -n "${mnt_storage}" ]]; then
+            echo "Disk is full, please rerun the workflow."
+            exit 1
+          fi
+          
+          sudo mkdir -p /mnt/new-storage
+          sudo touch /etc/docker/daemon.json
+          sudo tee /etc/docker/daemon.json <<EOF
+          {
+            "data-root": "/mnt/new-storage"
+          }
+          EOF
+          sudo systemctl restart docker
+          echo "Free space second:"
+          df -h
+          
       - name: get version
         id: get-version
         run: |
@@ -95,7 +102,7 @@ jobs:
           ref: ${{ steps.get-version.outputs.release-version }}
 
       - uses: docker/setup-qemu-action@v3
-      - if: ${{ env.DOCKER_USER != '' && env.DOCKER_PASSWORD != '' && (inputs.ENABLE_ADDONS == 'damengdb' || inputs.ENABLE_ADDONS == 'goldendb') }}
+      - if: ${{ env.DOCKER_USER != '' && env.DOCKER_PASSWORD != '' && (inputs.ENABLE_ADDONS == 'damengdb' || inputs.ENABLE_ADDONS == 'goldendb' || inputs.ENABLE_ADDONS == 'oceanbase' || inputs.ENABLE_ADDONS == 'hadoop' || inputs.ENABLE_ADDONS == 'hive' || inputs.ENABLE_ADDONS == 'kubeblocks-enterprise' || inputs.ENABLE_ADDONS == 'ape-local-csi-driver' || inputs.ENABLE_ADDONS == '') }}
         name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
@@ -130,8 +137,17 @@ jobs:
           ENABLE_ADDONS="${{ inputs.ENABLE_ADDONS }}"
        
           echo "save manifests images"
-          bash .github/scripts/manifests_images_save.sh "${MANIFESTS_FILE}" "${VALUES_FILE}" "${RELEASE_VERSION}" "${IMAGES_NAME}" "${IS_ADDON}" "${ENABLE_ADDONS}"
+          bash .github/scripts/manifests_images_save.sh "${MANIFESTS_FILE}" "${VALUES_FILE}" "${RELEASE_VERSION}" "${IMAGES_NAME}" "${IS_ADDON}" "${ENABLE_ADDONS}" "true"
+          
+          echo "Free space:"
+          df -h
 
+      - uses: manyuanrong/setup-ossutil@v2.0
+        with:
+          access-key-id: "${{ env.OSS_KEY_ID }}"
+          access-key-secret: "${{ env.OSS_KEY_SECRET }}"
+          endpoint: "${{ env.OSS_ENDPOINT }}"
+          
       - name: Upload manifests to oss
         run: |
           MANIFESTS_FILE="${{ env.MANIFESTS_FILE }}"
@@ -160,7 +176,7 @@ jobs:
           upload_ret=0
           for i in {1..10}; do
               echo "ossutil cp ${IMAGE_PKG_NAME} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME} ..."
-              ossutil cp -rf ./${IMAGE_PKG_NAME} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME}  --read-timeout=420 --retry-times=5
+              ossutil cp -rf ./${IMAGE_PKG_NAME} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME}
               upload_ret=$?
           
               if [[ -d "ossutil_output" ]]; then
@@ -186,20 +202,46 @@ jobs:
           else
               exit 1
           fi
-
-      - name: get self runner name
-        id: get_runner_name
-        if: ${{ always() }}
-        run: |
-          echo runner-name=${RUNNER_NAME} >> $GITHUB_OUTPUT
-
-  delete-self-runner:
-    if: ${{ always() }}
-    needs: [ save-images ]
-    uses: apecloud-inc/apecloud-cd/.github/workflows/delete-self-runner.yml@v0.5.0
-    with:
-      RUNNER_NAME: "${{ needs.save-images.outputs.runner-name }}"
-    secrets: inherit
+          
+          IMAGE_PKG_NAME_MD="${IMAGE_PKG_NAME}.md5"
+          echo "upload ${IMAGE_PKG_NAME_MD} to oss ..."
+          upload_ret=0
+          for i in {1..10}; do
+              md5sum ${IMAGE_PKG_NAME} > ${IMAGE_PKG_NAME_MD}
+              md5sum_check=$(md5sum -c ${IMAGE_PKG_NAME_MD})
+              check_ret=$?
+              if [[ $check_ret -eq 0 && "${md5sum_check}" == *"OK" ]]; then
+                  echo "${md5sum_check}"
+              else
+                  sleep 1
+                  continue
+              fi
+          
+              echo "ossutil cp ${IMAGE_PKG_NAME_MD} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_MD} ..."
+              ossutil cp -rf ./${IMAGE_PKG_NAME_MD} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_MD}
+              upload_ret=$?
+          
+              if [[ -d "ossutil_output" ]]; then
+                  ossutil_report_files=$(ls ossutil_output)
+                  if [[ -n "${ossutil_report_files}" ]]; then
+                      ossutil_report_file_name="$(ls ossutil_output/ossutil_report_*.report)"
+                      if [[ -n "${ossutil_report_file_name}" && -f "${ossutil_report_file_name}" ]]; then
+                          echo "cp ${IMAGE_PKG_NAME_MD} to oss error, retry..."
+                          cat "${ossutil_report_file_name}"
+                          rm -rf ossutil_output/ossutil_report_*.report
+                          upload_ret=1
+                      fi
+                  fi
+              fi
+              if [[ $upload_ret -eq 0 ]]; then
+                  break
+              fi
+              sleep 1
+          done
+          
+          if [[ $upload_ret -eq 0 ]]; then
+              echo "upload ${IMAGE_PKG_NAME_MD} to oss successfully"
+          fi
 
   save-result:
     runs-on: ubuntu-latest
diff --git a/.github/workflows/save-images-arm64.yml b/.github/workflows/save-images-arm64.yml
--- a/.github/workflows/save-images-arm64.yml
+++ b/.github/workflows/save-images-arm64.yml
@@ -9,31 +9,22 @@ on:
         default: 'kubeblocks-enterprise'
         type: choice
         options:
-          - dm
-          - busybox
-          - syncer
-          - redisinsight
-          - oteld
-          - clickhouse-22.3
-          - kubebench-0.0.10
-          - cilium
-          - swhy-upgrade
-          - damengdb-8.1.4
-          - cr-exporter
-          - elasticsearch-arm
-          - mysql-arm
-          - mongodb-arm
-          - damengdb-arm
           - kubeblocks-enterprise
           - kubeblocks-enterprise-patch
           - kubeblocks
           - kubeblocks-cloud
           - cert-manager
+          - doris
           - gemini
-          - apecloud-mysql
+          - elasticsearch-arm
+          - mysql-arm
+          - mongodb-arm
+          - damengdb-arm
           - clickhouse
           - gaussdb
-          - greatsql
+          - greatdb
+          - hadoop
+          - hive
           - influxdb
           - etcd
           - kafka
@@ -42,7 +33,6 @@ on:
           - loki
           - milvus
           - minio
-          - mongodb
           - metallb
           - mssql
           - nebula
@@ -55,7 +45,6 @@ on:
           - ape-local-csi-driver
           - spiderpool
           - metrics-server
-          - elasticsearch
           - kubechat
           - postgres-operator
           - rabbitmq
@@ -72,6 +61,15 @@ on:
           - csi-driver-nfs
           - dbdrag
           - pv-migrate
+      APP_DIR:
+        description: 'select addon dir'
+        required: false
+        default: ''
+        type: choice
+        options:
+          - ''
+          - '0.9'
+          - '1.0'
       APP_VERSION:
         description: 'app version'
         required: true
@@ -114,35 +112,31 @@ env:
   OSS_BUCKET: "kubeblocks-oss"
 
 jobs:
-  enable-self-runner:
-    uses: apecloud-inc/apecloud-cd/.github/workflows/enable-self-runner.yml@v0.4.0
-    with:
-      CLOUD_PROVIDER: "eks"
-      GITHUB_REPO: "apecloud-inc/kubeblocks-airgap"
-      RUNNER_LABEL: "kubeblocks-airgap-yq-arm-runner"
-      RUNNER_REPLICAS: 1
-    secrets: inherit
-
   save-app-images:
-    needs: [ enable-self-runner ]
     name: save app images
-    runs-on: [ self-hosted, arm-yq-runner ]
-    outputs:
-      runner-name: ${{ steps.get_runner_name.outputs.runner-name }}
+    runs-on: ubuntu-22.04
     steps:
-      - name: setup ossutil
-        continue-on-error: true
+      - name: Free disk space
         run: |
-          sudo apt-get update
-          sudo apt-get install unzip
-          sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
-
-      - name: ossutil config
-        env:
-          OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
-          OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}
-        run: |
-          ossutil config --access-key-id="${{ env.OSS_KEY_ID }}" --access-key-secret="${{ env.OSS_KEY_SECRET }}" --endpoint="${{ env.OSS_ENDPOINT }}"
+          echo "Free space first:"
+          df -h
+          
+          mnt_storage=$(df -h | (grep "/mnt" | grep "100%" ||true))
+          if [[ -n "${mnt_storage}" ]]; then
+            echo "Disk is full, please rerun the workflow."
+            exit 1
+          fi
+          
+          sudo mkdir -p /mnt/new-storage
+          sudo touch /etc/docker/daemon.json
+          sudo tee /etc/docker/daemon.json <<EOF
+          {
+            "data-root": "/mnt/new-storage"
+          }
+          EOF
+          sudo systemctl restart docker
+          echo "Free space second:"
+          df -h
 
       - uses: actions/checkout@v4
       - uses: docker/setup-qemu-action@v3
@@ -156,6 +150,17 @@ jobs:
               RELEASE_VERSION="v${RELEASE_VERSION}"
           fi
           echo "release-version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
+
+      - name: get images file
+        id: get-images-file
+        run: |
+          APP_DIR="${{ inputs.APP_DIR }}"
+          APP_NAME="${{ inputs.APP_NAME }}"
+          IMAGES_FILE=".github/images/${APP_NAME}.txt"
+          if [[ -n "${APP_DIR}" ]]; then
+              IMAGES_FILE=".github/images/${APP_DIR}/${APP_NAME}.txt"
+          fi
+          echo "images-file=${IMAGES_FILE}" >> $GITHUB_OUTPUT
 
       - name: Checkout apecloud Code
         uses: actions/checkout@v4
@@ -183,7 +188,8 @@ jobs:
           oteld_version: ${{ inputs.OTELD_VERSION }}
           installer_version: ${{ inputs.INSTALLER_VERSION }}
           dms_version: ${{ inputs.DMS_VERSION }}
-          images_file: .github/images/${{ inputs.APP_NAME }}.txt
+          images_file: ${{ steps.get-images-file.outputs.images-file }}
+          platform: "linux/arm64"
         run: |
           bash .github/scripts/save_images.sh
 
@@ -192,9 +198,17 @@ jobs:
           docker images
           du -sh ${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tar.gz 
 
+      - uses: manyuanrong/setup-ossutil@v2.0
+        with:
+          access-key-id: "${{ env.OSS_KEY_ID }}"
+          access-key-secret: "${{ env.OSS_KEY_SECRET }}"
+          endpoint: "${{ env.OSS_ENDPOINT }}"
+
       - name: Upload arm64 images to oss
         id: upload_to_oss
         run: |
+          echo "Free space:"
+          df -h
           IMAGE_PKG_NAME="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tar.gz"
           IMAGE_PKG_NAME_ARM64="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}-arm64.tar.gz"
           mv ${IMAGE_PKG_NAME} ${IMAGE_PKG_NAME_ARM64}
@@ -202,7 +216,7 @@ jobs:
           upload_ret=0
           for i in {1..10}; do
               echo "ossutil cp ${IMAGE_PKG_NAME_ARM64} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_ARM64} ..."
-              ossutil cp -rf ./${IMAGE_PKG_NAME_ARM64} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_ARM64}  --read-timeout=420 --retry-times=5
+              ossutil cp -rf ./${IMAGE_PKG_NAME_ARM64} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_ARM64}
               upload_ret=$?
                 
               if [[ -d "ossutil_output" ]]; then
@@ -228,20 +242,46 @@ jobs:
           else
               exit 1
           fi
-
-      - name: get self runner name
-        id: get_runner_name
-        if: ${{ always() }}
-        run: |
-          echo runner-name=${RUNNER_NAME} >> $GITHUB_OUTPUT
-
-  delete-self-runner:
-    if: ${{ always() }}
-    needs: [ save-app-images ]
-    uses: apecloud-inc/apecloud-cd/.github/workflows/delete-self-runner.yml@v0.5.0
-    with:
-      RUNNER_NAME: "${{ needs.save-app-images.outputs.runner-name }}"
-    secrets: inherit
+      
+          IMAGE_PKG_NAME_MD="${IMAGE_PKG_NAME_ARM64}.md5"
+          echo "upload ${IMAGE_PKG_NAME_MD} to oss ..."
+          upload_ret=0
+          for i in {1..10}; do
+              md5sum ${IMAGE_PKG_NAME_ARM64} > ${IMAGE_PKG_NAME_MD}
+              md5sum_check=$(md5sum -c ${IMAGE_PKG_NAME_MD})
+              check_ret=$?
+              if [[ $check_ret -eq 0 && "${md5sum_check}" == *"OK" ]]; then
+                  echo "${md5sum_check}"
+              else
+                  sleep 1
+                  continue
+              fi
+          
+              echo "ossutil cp ${IMAGE_PKG_NAME_MD} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_MD} ..."
+              ossutil cp -rf ./${IMAGE_PKG_NAME_MD} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_MD}
+              upload_ret=$?
+          
+              if [[ -d "ossutil_output" ]]; then
+                  ossutil_report_files=$(ls ossutil_output)
+                  if [[ -n "${ossutil_report_files}" ]]; then
+                      ossutil_report_file_name="$(ls ossutil_output/ossutil_report_*.report)"
+                      if [[ -n "${ossutil_report_file_name}" && -f "${ossutil_report_file_name}" ]]; then
+                          echo "cp ${IMAGE_PKG_NAME_MD} to oss error, retry..."
+                          cat "${ossutil_report_file_name}"
+                          rm -rf ossutil_output/ossutil_report_*.report
+                          upload_ret=1
+                      fi
+                  fi
+              fi
+              if [[ $upload_ret -eq 0 ]]; then
+                  break
+              fi
+              sleep 1
+          done
+          
+          if [[ $upload_ret -eq 0 ]]; then
+              echo "upload ${IMAGE_PKG_NAME_MD} to oss successfully"
+          fi
 
   save-result:
     runs-on: ubuntu-latest
@@ -275,14 +315,29 @@ jobs:
       CONTENT: "save image ${{ needs.save-result.outputs.image-pkg-name }} ${{ needs.save-result.outputs.save-result }}"
     secrets: inherit
 
-  disable-self-runner:
-    if: ${{ always() }}
+  upload-md5-checksums:
     needs: [ save-app-images ]
-    uses: apecloud-inc/apecloud-cd/.github/workflows/enable-self-runner.yml@v0.4.0
-    with:
-      CLOUD_PROVIDER: "eks"
-      GITHUB_REPO: "apecloud-inc/kubeblocks-airgap"
-      RUNNER_LABEL: "kubeblocks-airgap-yq-arm-runner"
-      ENABLE: "disable"
-    secrets: inherit
-
+    permissions:
+      contents: write
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: auto release images
+        run: |
+          cmd="bash .github/scripts/trigger_workflow.sh "
+          cmd=$cmd"--github-token \"${{ env.GITHUB_TOKEN }}\" "
+          cmd=$cmd"--github-repo \"${{ github.repository }}\" "
+          cmd=$cmd"--branch-name \"${{ github.ref_name }}\" "
+          cmd=$cmd"--workflow-id \"save-md5-checksums.yml\" "
+          
+          APP_NAME="${{ inputs.APP_NAME }}"
+          RELEASE_VERSION="${{ inputs.APP_VERSION }}"
+          if [[ "${RELEASE_VERSION}" != "v"* ]]; then
+              RELEASE_VERSION="v${RELEASE_VERSION}"
+          fi
+          if [[ "${APP_NAME}" == "kubeblocks-enterprise" && -n "${RELEASE_VERSION}" ]]; then
+              cmd=$cmd"--version \"${RELEASE_VERSION}\" "
+          fi
+          
+          echo "$cmd"
+          eval "$cmd"
