chore: release cilium v1.14.8

diff --git a/.github/workflows/manifests-images-save-arm64.yml b/.github/workflows/manifests-images-save-arm64.yml
--- a/.github/workflows/manifests-images-save-arm64.yml
+++ b/.github/workflows/manifests-images-save-arm64.yml
@@ -1,4 +1,4 @@
-name: Manifests Images Save
+name: Manifests Images Save  Arm64
 
 on:
   workflow_dispatch:
@@ -56,29 +56,25 @@ env:
 
 jobs:
   save-images:
-    runs-on: ubuntu-22.04
+    runs-on: [ self-hosted, arm-yq-runner ]
     outputs:
       release-version: ${{ steps.get-version.outputs.release-version }}
       image-name: ${{ steps.get-image-name.outputs.image-name }}
+      runner-name: ${{ steps.get_runner_name.outputs.runner-name }}
     steps:
-      - name: Free disk space
+      - name: setup ossutil
+        continue-on-error: true
         run: |
-          sudo apt-get autoremove -y >/dev/null 2>&1
-          sudo apt-get autoclean -y >/dev/null 2>&1
-          sudo rm -rf /usr/local/lib/android >/dev/null 2>&1
-          docker rmi $(docker image ls -aq) >/dev/null 2>&1
-          sudo swapoff -a
-          sudo rm -f /swapfile
-          df -h
-          
-          sudo mkdir -p /mnt/new-storage
-          sudo touch /etc/docker/daemon.json
-          sudo tee /etc/docker/daemon.json <<EOF
-          {
-            "data-root": "/mnt/new-storage"
-          }
-          EOF
-          sudo systemctl restart docker
+          sudo apt-get update
+          sudo apt-get install unzip
+          sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
+
+      - name: ossutil config
+        env:
+          OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
+          OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}
+        run: |
+          ossutil config --access-key-id="${{ env.OSS_KEY_ID }}" --access-key-secret="${{ env.OSS_KEY_SECRET }}" --endpoint="${{ env.OSS_ENDPOINT }}"
 
       - name: get version
         id: get-version
@@ -90,7 +86,6 @@ jobs:
           echo "release-version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
 
       - uses: actions/checkout@v4
-
       - name: Checkout apecloud Code
         uses: actions/checkout@v4
         with:
@@ -98,6 +93,15 @@ jobs:
           path: apecloud
           token: ${{ env.GITHUB_TOKEN }}
           ref: ${{ steps.get-version.outputs.release-version }}
+
+      - uses: docker/setup-qemu-action@v3
+      - if: ${{ env.DOCKER_USER != '' && env.DOCKER_PASSWORD != '' && (inputs.ENABLE_ADDONS == 'damengdb' || inputs.ENABLE_ADDONS == 'goldendb') }}
+        name: Login to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          registry: ${{ env.DOCKER_REGISTRY_URL }}
+          username: ${{ env.DOCKER_USER }}
+          password: ${{ env.DOCKER_PASSWORD }}
 
       - name: get image name
         id: get-image-name
@@ -127,15 +131,6 @@ jobs:
        
           echo "save manifests images"
           bash .github/scripts/manifests_images_save.sh "${MANIFESTS_FILE}" "${VALUES_FILE}" "${RELEASE_VERSION}" "${IMAGES_NAME}" "${IS_ADDON}" "${ENABLE_ADDONS}"
-          
-          echo "Free space:"
-          df -h
-
-      - uses: manyuanrong/setup-ossutil@v2.0
-        with:
-          access-key-id: "${{ env.OSS_KEY_ID }}"
-          access-key-secret: "${{ env.OSS_KEY_SECRET }}"
-          endpoint: "${{ env.OSS_ENDPOINT }}"
 
       - name: Upload manifests to oss
         run: |
@@ -157,17 +152,54 @@ jobs:
               exit 1
           fi
 
-      - name: Upload images to oss
+      - name: Upload arm64 images to oss
         id: upload_to_oss
         run: |
           IMAGE_PKG_NAME="${{ steps.get-image-name.outputs.image-name }}-images-${{ steps.get-version.outputs.release-version }}.tar.gz"
-          ossutil cp -rf ./${IMAGE_PKG_NAME} oss://${{ env.OSS_BUCKET }}/images/${IMAGE_PKG_NAME}
-          upload_ret=$?
+          
+          upload_ret=0
+          for i in {1..10}; do
+              echo "ossutil cp ${IMAGE_PKG_NAME} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME} ..."
+              ossutil cp -rf ./${IMAGE_PKG_NAME} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME}  --read-timeout=420 --retry-times=5
+              upload_ret=$?
+          
+              if [[ -d "ossutil_output" ]]; then
+                  ossutil_report_files=$(ls ossutil_output)
+                  if [[ -n "${ossutil_report_files}" ]]; then
+                      ossutil_report_file_name="$(ls ossutil_output/ossutil_report_*.report)"
+                      if [[ -n "${ossutil_report_file_name}" && -f "${ossutil_report_file_name}" ]]; then
+                          echo "cp ${IMAGE_PKG_NAME} to oss error, retry..."
+                          cat "${ossutil_report_file_name}"
+                          rm -rf ossutil_output/ossutil_report_*.report
+                          upload_ret=1
+                      fi
+                  fi
+              fi
+              if [[ $upload_ret -eq 0 ]]; then
+                  break
+              fi
+              sleep 1
+          done
+          
           if [[ $upload_ret -eq 0 ]]; then
               echo "upload ${IMAGE_PKG_NAME} to oss successfully"
           else
               exit 1
           fi
+
+      - name: get self runner name
+        id: get_runner_name
+        if: ${{ always() }}
+        run: |
+          echo runner-name=${RUNNER_NAME} >> $GITHUB_OUTPUT
+
+  delete-self-runner:
+    if: ${{ always() }}
+    needs: [ save-images ]
+    uses: apecloud-inc/apecloud-cd/.github/workflows/delete-self-runner.yml@v0.5.0
+    with:
+      RUNNER_NAME: "${{ needs.save-images.outputs.runner-name }}"
+    secrets: inherit
 
   save-result:
     runs-on: ubuntu-latest
@@ -184,7 +216,7 @@ jobs:
           IMAGE_PKG_NAME="${{ needs.save-images.outputs.image-name }}-images-${{ needs.save-images.outputs.release-version }}.tar.gz"
           if [[ "${{ needs.save-images.result }}" == "success" ]]; then
               SAVE_RESULT="success"
-              IMAGE_PKG_NAME="http://kubeblocks-oss.${{ env.OSS_ENDPOINT }}/images/${IMAGE_PKG_NAME}"
+              IMAGE_PKG_NAME="http://kubeblocks-oss.${{ env.OSS_ENDPOINT }}/images/arm64/${IMAGE_PKG_NAME}"
           fi
           echo 'save_result='$SAVE_RESULT >> $GITHUB_OUTPUT
           echo 'image_pkg_name='${IMAGE_PKG_NAME} >> $GITHUB_OUTPUT
