chore: fix save images error

diff --git a/.github/workflows/save-images.yml b/.github/workflows/save-images.yml
--- a/.github/workflows/save-images.yml
+++ b/.github/workflows/save-images.yml
@@ -226,7 +226,13 @@ jobs:
       - name: get images size
         run: |
           docker images
-          du -sh ${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tar.gz
+          IMAGE_PKG="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tar.gz"
+          du -sh "${IMAGE_PKG}"
+          SIZE=$(du -b "${IMAGE_PKG}" | awk '{print $1}')
+          if [[ "${SIZE}" -le 4096 ]]; then
+              echo "Error: ${IMAGE_PKG} size is ${SIZE} bytes, which indicates the save failed. Exiting."
+              exit 1
+          fi
 
       - uses: manyuanrong/setup-ossutil@v2.0
         with:
