chore: release kubeblocks-sealos-sailisi 0.9.4

diff --git a/.github/workflows/save-images-arm64-patch.yml b/.github/workflows/save-images-arm64-patch.yml
--- a/.github/workflows/save-images-arm64-patch.yml
+++ b/.github/workflows/save-images-arm64-patch.yml
@@ -1,4 +1,4 @@
-name: Save Images
+name: Save Images Arm64 Patch
 
 on:
   workflow_dispatch:
@@ -6,94 +6,10 @@ on:
       APP_NAME:
         description: 'app name'
         required: true
-        default: 'kubeblocks-enterprise'
+        default: 'kubeblocks-enterprise-patch'
         type: choice
         options:
-          - kubeblocks-sealos-sailisi
-          - k3s
-          - kubernetes
-          - servicemirror
-          - kb-cloud-docs
-          - redisinsight
-          - dms
-          - redis-stack-server
-          - oteld
-          - gemini-oteld
-          - clickhouse-22.3
-          - minio-cpuv1
-          - kubebench-0.0.10
-          - cilium
-          - kubeblocks-installer
-          - kubeblocks-tools
-          - openconsole
-          - syncer
-          - kubeblocks-enterprise
           - kubeblocks-enterprise-patch
-          - kubeblocks
-          - kubeblocks-cloud
-          - cert-manager
-          - gemini
-          - ape-local-csi-driver
-          - apecloud-mysql
-          - clickhouse
-          - damengdb
-          - influxdb
-          - etcd
-          - elasticsearch
-          - gaussdb
-          - gbase
-          - goldendb
-          - greatsql
-          - kafka
-          - kata
-          - kingbase
-          - kubebench
-          - kubechat
-          - k3s
-          - kubernetes
-          - loki
-          - milvus
-          - minio
-          - mongodb
-          - mssql
-          - mysql
-          - metallb
-          - metrics-server
-          - nebula
-          - oceanbase
-          - oceanbase-proxy
-          - oracle
-          - postgresql
-          - postgres-operator
-          - qdrant
-          - rabbitmq
-          - rocketmq
-          - redis
-          - starrocks
-          - starrocks-3.2.2
-          - starrocks-3.3.0
-          - starrocks-3.3.2
-          - starrocks-3.3.3
-          - starrocks-3.4.1
-          - spiderpool
-          - victoria-metrics
-          - xinference-cpu
-          - xinference-gpu
-          - zookeeper
-          - ingress-nginx
-          - nvidia-device-plugin
-          - dify
-          - tdengine
-          - tdsql
-          - tidb
-          - vastbase
-          - mogdb
-          - polardbx
-          - pulsar
-          - calico
-          - csi-driver-nfs
-          - dbdrag
-          - pv-migrate
       APP_VERSION:
         description: 'app version'
         required: true
@@ -123,7 +39,7 @@ on:
         required: false
         default: ''
 
-run-name: save ${{ inputs.APP_NAME }}:${{ inputs.APP_VERSION }} ${{ inputs.ADD_IMAGES }}
+run-name: save Arm64 ${{ inputs.APP_NAME }}:${{ inputs.APP_VERSION }} ${{ inputs.ADD_IMAGES }}
 
 env:
   DOCKER_REGISTRY_URL: docker.io
@@ -136,38 +52,35 @@ env:
   OSS_BUCKET: "kubeblocks-oss"
 
 jobs:
+  enable-self-runner:
+    uses: apecloud-inc/apecloud-cd/.github/workflows/enable-self-runner.yml@v0.4.0
+    with:
+      CLOUD_PROVIDER: "eks"
+      GITHUB_REPO: "apecloud-inc/kubeblocks-airgap"
+      RUNNER_LABEL: "kubeblocks-airgap-yq-arm-runner"
+      RUNNER_REPLICAS: 1
+    secrets: inherit
+
   save-app-images:
+    needs: [ enable-self-runner ]
     name: save app images
-    runs-on: ubuntu-22.04
+    runs-on: [ self-hosted, arm-yq-runner ]
+    outputs:
+      runner-name: ${{ steps.get_runner_name.outputs.runner-name }}
     steps:
-      - name: Free disk space
+      - name: setup ossutil
+        continue-on-error: true
         run: |
-          if [[ "${{ inputs.APP_NAME }}" == "mysql" || "${{ inputs.APP_NAME }}" == "starrocks" || "${{ inputs.APP_NAME }}" == "goldendb" || "${{ inputs.APP_NAME }}" == "dbdrag" || "${{ inputs.APP_NAME }}" == "elasticsearch" || "${{ inputs.APP_NAME }}" == "xinference-gpu" ]]; then
-              sudo apt-get autoremove -y >/dev/null 2>&1
-              sudo apt-get autoclean -y >/dev/null 2>&1
-              sudo rm -rf /usr/local/lib/android >/dev/null 2>&1
-              docker rmi $(docker image ls -aq) >/dev/null 2>&1
-              sudo swapoff -a
-              sudo rm -f /swapfile
-              df -h
-          
-              sudo mkdir -p /mnt/new-storage
-              sudo touch /etc/docker/daemon.json
-              sudo tee /etc/docker/daemon.json <<EOF
-          {
-            "data-root": "/mnt/new-storage"
-          }
-          EOF
-              sudo systemctl restart docker
-          elif [[ "${{ inputs.APP_NAME }}" == "kubeblocks-enterprise" || "${{ inputs.APP_NAME }}" == "starrocks"* || "${{ inputs.APP_NAME }}" == "mongodb" ]]; then
-              sudo apt-get autoremove -y >/dev/null 2>&1
-              sudo apt-get autoclean -y >/dev/null 2>&1
-              sudo rm -rf /usr/local/lib/android >/dev/null 2>&1
-              docker rmi $(docker image ls -aq) >/dev/null 2>&1
-              sudo swapoff -a
-              sudo rm -f /swapfile
-              df -h
-          fi
+          sudo apt-get update
+          sudo apt-get install unzip
+          sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
+
+      - name: ossutil config
+        env:
+          OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
+          OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}
+        run: |
+          ossutil config --access-key-id="${{ env.OSS_KEY_ID }}" --access-key-secret="${{ env.OSS_KEY_SECRET }}" --endpoint="${{ env.OSS_ENDPOINT }}"
 
       - uses: actions/checkout@v4
       - uses: docker/setup-qemu-action@v3
@@ -215,27 +128,58 @@ jobs:
       - name: get images size
         run: |
           docker images
-          du -sh ${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tar.gz
+          du -sh ${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tar.gz 
 
-      - uses: manyuanrong/setup-ossutil@v2.0
-        with:
-          access-key-id: "${{ secrets.OSS_KEY_ID }}"
-          access-key-secret: "${{ secrets.OSS_KEY_SECRET }}"
-          endpoint: "${{ env.OSS_ENDPOINT }}"
-
-      - name: Upload images to oss
+      - name: Upload arm64 images to oss
         id: upload_to_oss
         run: |
-          echo "Free space:"
-          df -h
           IMAGE_PKG_NAME="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tar.gz"
-          ossutil cp -rf ./${IMAGE_PKG_NAME} oss://${{ env.OSS_BUCKET }}/images/${IMAGE_PKG_NAME}
-          upload_ret=$?
+          IMAGE_PKG_NAME_ARM64="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}-arm64.tar.gz"
+          mv ${IMAGE_PKG_NAME} ${IMAGE_PKG_NAME_ARM64}
+          
+          upload_ret=0
+          for i in {1..10}; do
+              echo "ossutil cp ${IMAGE_PKG_NAME_ARM64} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_ARM64} ..."
+              ossutil cp -rf ./${IMAGE_PKG_NAME_ARM64} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_ARM64}  --read-timeout=420 --retry-times=5
+              upload_ret=$?
+                
+              if [[ -d "ossutil_output" ]]; then
+                  ossutil_report_files=$(ls ossutil_output)
+                  if [[ -n "${ossutil_report_files}" ]]; then
+                      ossutil_report_file_name="$(ls ossutil_output/ossutil_report_*.report)"
+                      if [[ -n "${ossutil_report_file_name}" && -f "${ossutil_report_file_name}" ]]; then
+                          echo "cp ${IMAGE_PKG_NAME_ARM64} to oss error, retry..."
+                          cat "${ossutil_report_file_name}"
+                          rm -rf ossutil_output/ossutil_report_*.report
+                          upload_ret=1
+                      fi
+                  fi
+              fi
+              if [[ $upload_ret -eq 0 ]]; then
+                  break
+              fi
+              sleep 1
+          done
+          
           if [[ $upload_ret -eq 0 ]]; then
-              echo "upload ${IMAGE_PKG_NAME} to oss successfully"
+              echo "upload ${IMAGE_PKG_NAME_ARM64} to oss successfully"
           else
               exit 1
           fi
+
+      - name: get self runner name
+        id: get_runner_name
+        if: ${{ always() }}
+        run: |
+          echo runner-name=${RUNNER_NAME} >> $GITHUB_OUTPUT
+
+  delete-self-runner:
+    if: ${{ always() }}
+    needs: [ save-app-images ]
+    uses: apecloud-inc/apecloud-cd/.github/workflows/delete-self-runner.yml@v0.5.0
+    with:
+      RUNNER_NAME: "${{ needs.save-app-images.outputs.runner-name }}"
+    secrets: inherit
 
   save-result:
     runs-on: ubuntu-latest
@@ -249,13 +193,13 @@ jobs:
         id: get_save_result
         run: |
           SAVE_RESULT="error"
-          IMAGE_PKG_NAME="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tar.gz"
+          IMAGE_PKG_NAME_ARM64="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}-arm64.tar.gz"
           if [[ "${{ needs.save-app-images.result }}" == "success" ]]; then
               SAVE_RESULT="success"
-              IMAGE_PKG_NAME="http://kubeblocks-oss.${{ env.OSS_ENDPOINT }}/images/${IMAGE_PKG_NAME}"
+              IMAGE_PKG_NAME_ARM64="http://kubeblocks-oss.${{ env.OSS_ENDPOINT }}/images/arm64/${IMAGE_PKG_NAME_ARM64}"
           fi
           echo 'save_result='$SAVE_RESULT >> $GITHUB_OUTPUT
-          echo 'image_pkg_name='${IMAGE_PKG_NAME} >> $GITHUB_OUTPUT
+          echo 'image_pkg_name='${IMAGE_PKG_NAME_ARM64} >> $GITHUB_OUTPUT
 
   send-message:
     permissions:
@@ -268,3 +212,15 @@ jobs:
       TYPE: "2"
       CONTENT: "save image ${{ needs.save-result.outputs.image-pkg-name }} ${{ needs.save-result.outputs.save-result }}"
     secrets: inherit
+
+  disable-self-runner:
+    if: ${{ always() }}
+    needs: [ save-app-images ]
+    uses: apecloud-inc/apecloud-cd/.github/workflows/enable-self-runner.yml@v0.4.0
+    with:
+      CLOUD_PROVIDER: "eks"
+      GITHUB_REPO: "apecloud-inc/kubeblocks-airgap"
+      RUNNER_LABEL: "kubeblocks-airgap-yq-arm-runner"
+      ENABLE: "disable"
+    secrets: inherit
+
