chore: docker pull platform

diff --git a/.github/workflows/save-images-arm64.yml b/.github/workflows/save-images-arm64.yml
--- a/.github/workflows/save-images-arm64.yml
+++ b/.github/workflows/save-images-arm64.yml
@@ -140,6 +140,7 @@ jobs:
           installer_version: ${{ inputs.INSTALLER_VERSION }}
           dms_version: ${{ inputs.DMS_VERSION }}
           images_file: .github/images/${{ inputs.APP_NAME }}.txt
+          image_platform: "linux/arm64"
         run: |
           bash .github/scripts/save_images.sh
 
@@ -148,97 +149,97 @@ jobs:
           docker images
           du -sh ${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tar.gz 
 
-      - name: Upload arm64 images to oss
-        id: upload_to_oss
-        run: |
-          IMAGE_PKG_NAME="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tar.gz"
-          IMAGE_PKG_NAME_ARM64="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}-arm64.tar.gz"
-          mv ${IMAGE_PKG_NAME} ${IMAGE_PKG_NAME_ARM64}
-          
-          upload_ret=0
-          for i in {1..10}; do
-              echo "ossutil cp ${IMAGE_PKG_NAME_ARM64} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_ARM64} ..."
-              ossutil cp -rf ./${IMAGE_PKG_NAME_ARM64} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_ARM64}  --read-timeout=420 --retry-times=5
-              upload_ret=$?
-                
-              if [[ -d "ossutil_output" ]]; then
-                  ossutil_report_files=$(ls ossutil_output)
-                  if [[ -n "${ossutil_report_files}" ]]; then
-                      ossutil_report_file_name="$(ls ossutil_output/ossutil_report_*.report)"
-                      if [[ -n "${ossutil_report_file_name}" && -f "${ossutil_report_file_name}" ]]; then
-                          echo "cp ${IMAGE_PKG_NAME_ARM64} to oss error, retry..."
-                          cat "${ossutil_report_file_name}"
-                          rm -rf ossutil_output/ossutil_report_*.report
-                          upload_ret=1
-                      fi
-                  fi
-              fi
-              if [[ $upload_ret -eq 0 ]]; then
-                  break
-              fi
-              sleep 1
-          done
-          
-          if [[ $upload_ret -eq 0 ]]; then
-              echo "upload ${IMAGE_PKG_NAME_ARM64} to oss successfully"
-          else
-              exit 1
-          fi
-
-      - name: get self runner name
-        id: get_runner_name
-        if: ${{ always() }}
-        run: |
-          echo runner-name=${RUNNER_NAME} >> $GITHUB_OUTPUT
-
-  delete-self-runner:
-    if: ${{ always() }}
-    needs: [ save-app-images ]
-    uses: apecloud-inc/apecloud-cd/.github/workflows/delete-self-runner.yml@v0.5.0
-    with:
-      RUNNER_NAME: "${{ needs.save-app-images.outputs.runner-name }}"
-    secrets: inherit
-
-  save-result:
-    runs-on: ubuntu-latest
-    needs: [ save-app-images ]
-    if: ${{ always() }}
-    outputs:
-      image-pkg-name: ${{ steps.get_save_result.outputs.image_pkg_name }}
-      save-result: ${{ steps.get_save_result.outputs.save_result }}
-    steps:
-      - name: get save result
-        id: get_save_result
-        run: |
-          SAVE_RESULT="error"
-          IMAGE_PKG_NAME_ARM64="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}-arm64.tar.gz"
-          if [[ "${{ needs.save-app-images.result }}" == "success" ]]; then
-              SAVE_RESULT="success"
-              IMAGE_PKG_NAME_ARM64="http://kubeblocks-oss.${{ env.OSS_ENDPOINT }}/images/arm64/${IMAGE_PKG_NAME_ARM64}"
-          fi
-          echo 'save_result='$SAVE_RESULT >> $GITHUB_OUTPUT
-          echo 'image_pkg_name='${IMAGE_PKG_NAME_ARM64} >> $GITHUB_OUTPUT
-
-  send-message:
-    permissions:
-      id-token: write
-      contents: read
-    needs: [ save-result ]
-    if: ${{ always() }}
-    uses: apecloud-inc/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.0
-    with:
-      TYPE: "2"
-      CONTENT: "save image ${{ needs.save-result.outputs.image-pkg-name }} ${{ needs.save-result.outputs.save-result }}"
-    secrets: inherit
-
-  disable-self-runner:
-    if: ${{ always() }}
-    needs: [ save-app-images ]
-    uses: apecloud-inc/apecloud-cd/.github/workflows/enable-self-runner.yml@v0.4.0
-    with:
-      CLOUD_PROVIDER: "eks"
-      GITHUB_REPO: "apecloud-inc/kubeblocks-airgap"
-      RUNNER_LABEL: "kubeblocks-airgap-runner-arm64"
-      ENABLE: "disable"
-    secrets: inherit
+#      - name: Upload arm64 images to oss
+#        id: upload_to_oss
+#        run: |
+#          IMAGE_PKG_NAME="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tar.gz"
+#          IMAGE_PKG_NAME_ARM64="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}-arm64.tar.gz"
+#          mv ${IMAGE_PKG_NAME} ${IMAGE_PKG_NAME_ARM64}
+#
+#          upload_ret=0
+#          for i in {1..10}; do
+#              echo "ossutil cp ${IMAGE_PKG_NAME_ARM64} to oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_ARM64} ..."
+#              ossutil cp -rf ./${IMAGE_PKG_NAME_ARM64} oss://${{ env.OSS_BUCKET }}/images/arm64/${IMAGE_PKG_NAME_ARM64}  --read-timeout=420 --retry-times=5
+#              upload_ret=$?
+#
+#              if [[ -d "ossutil_output" ]]; then
+#                  ossutil_report_files=$(ls ossutil_output)
+#                  if [[ -n "${ossutil_report_files}" ]]; then
+#                      ossutil_report_file_name="$(ls ossutil_output/ossutil_report_*.report)"
+#                      if [[ -n "${ossutil_report_file_name}" && -f "${ossutil_report_file_name}" ]]; then
+#                          echo "cp ${IMAGE_PKG_NAME_ARM64} to oss error, retry..."
+#                          cat "${ossutil_report_file_name}"
+#                          rm -rf ossutil_output/ossutil_report_*.report
+#                          upload_ret=1
+#                      fi
+#                  fi
+#              fi
+#              if [[ $upload_ret -eq 0 ]]; then
+#                  break
+#              fi
+#              sleep 1
+#          done
+#
+#          if [[ $upload_ret -eq 0 ]]; then
+#              echo "upload ${IMAGE_PKG_NAME_ARM64} to oss successfully"
+#          else
+#              exit 1
+#          fi
+#
+#      - name: get self runner name
+#        id: get_runner_name
+#        if: ${{ always() }}
+#        run: |
+#          echo runner-name=${RUNNER_NAME} >> $GITHUB_OUTPUT
+#
+#  delete-self-runner:
+#    if: ${{ always() }}
+#    needs: [ save-app-images ]
+#    uses: apecloud-inc/apecloud-cd/.github/workflows/delete-self-runner.yml@v0.5.0
+#    with:
+#      RUNNER_NAME: "${{ needs.save-app-images.outputs.runner-name }}"
+#    secrets: inherit
+#
+#  save-result:
+#    runs-on: ubuntu-latest
+#    needs: [ save-app-images ]
+#    if: ${{ always() }}
+#    outputs:
+#      image-pkg-name: ${{ steps.get_save_result.outputs.image_pkg_name }}
+#      save-result: ${{ steps.get_save_result.outputs.save_result }}
+#    steps:
+#      - name: get save result
+#        id: get_save_result
+#        run: |
+#          SAVE_RESULT="error"
+#          IMAGE_PKG_NAME_ARM64="${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}-arm64.tar.gz"
+#          if [[ "${{ needs.save-app-images.result }}" == "success" ]]; then
+#              SAVE_RESULT="success"
+#              IMAGE_PKG_NAME_ARM64="http://kubeblocks-oss.${{ env.OSS_ENDPOINT }}/images/arm64/${IMAGE_PKG_NAME_ARM64}"
+#          fi
+#          echo 'save_result='$SAVE_RESULT >> $GITHUB_OUTPUT
+#          echo 'image_pkg_name='${IMAGE_PKG_NAME_ARM64} >> $GITHUB_OUTPUT
+#
+#  send-message:
+#    permissions:
+#      id-token: write
+#      contents: read
+#    needs: [ save-result ]
+#    if: ${{ always() }}
+#    uses: apecloud-inc/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.0
+#    with:
+#      TYPE: "2"
+#      CONTENT: "save image ${{ needs.save-result.outputs.image-pkg-name }} ${{ needs.save-result.outputs.save-result }}"
+#    secrets: inherit
+#
+#  disable-self-runner:
+#    if: ${{ always() }}
+#    needs: [ save-app-images ]
+#    uses: apecloud-inc/apecloud-cd/.github/workflows/enable-self-runner.yml@v0.4.0
+#    with:
+#      CLOUD_PROVIDER: "eks"
+#      GITHUB_REPO: "apecloud-inc/kubeblocks-airgap"
+#      RUNNER_LABEL: "kubeblocks-airgap-runner-arm64"
+#      ENABLE: "disable"
+#    secrets: inherit
 
